[project]
name = "jw-db-manager"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "flask>=2.0.0",
    "openpyxl>=3.0.0",
    "pandas>=1.3.0",
    "piexif>=1.1.3",
    "pillow>=11.2.1",
]
